"""add webhook_event table

Revision ID: e776e428dcf1
Revises: f5e8255ce9e4
Create Date: 2026-08-25 18:47:01.234276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e776e428dcf1'
down_revision: Union[str, Sequence[str], None] = 'f5e8255ce9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSED', 'SKIPPED_DUPLICATE', 'SKIPPED_UNHANDLED', 'FAILED', name='webhookeventstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_razorpay_event_id'), 'webhook_event', ['razorpay_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_razorpay_event_id'), table_name='webhook_event')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
