"""Add data quality metrics to batch

Revision ID: f4dd359791af
Revises: 26672c42bab3
Create Date: 2026-08-29 19:32:08.501496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4dd359791af'
down_revision: Union[str, Sequence[str], None] = '26672c42bab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('duplicate_ledger_order_ids', sa.Integer(), nullable=True))
    op.add_column('batch', sa.Column('skipped_rows', sa.Integer(), nullable=True))
    op.add_column('reconciliation_result', sa.Column('expected_amount_paise', sa.BigInteger(), nullable=True))
    op.add_column('reconciliation_result', sa.Column('actual_amount_paise', sa.BigInteger(), nullable=True))
    op.add_column('reconciliation_result', sa.Column('difference_paise', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_result', 'difference_paise')
    op.drop_column('reconciliation_result', 'actual_amount_paise')
    op.drop_column('reconciliation_result', 'expected_amount_paise')
    op.drop_column('batch', 'skipped_rows')
    op.drop_column('batch', 'duplicate_ledger_order_ids')
    # ### end Alembic commands ###
