"""initial_schema

Revision ID: f5e8255ce9e4
Revises: 
Create Date: 2026-08-25 01:05:35.390418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e8255ce9e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utr', sa.String(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_entry_utr'), 'bank_entry', ['utr'], unique=False)
    op.create_table('batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'INGESTING', 'INGESTED', 'RECONCILING', 'COMPLETED', 'FAILED_INGESTION', 'FAILED_RECONCILIATION', name='batchstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('expected_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('customer_ref', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entry_order_id'), 'ledger_entry', ['order_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_table('settlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_settlement_id', sa.String(), nullable=True),
    sa.Column('utr', sa.String(), nullable=False),
    sa.Column('gross_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('adjustment_paise', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_utr'), 'settlement', ['utr'], unique=False)
    op.create_table('reconciliation_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('result_scope', sa.Enum('PAYMENT', 'ORPHAN_BANK_ENTRY', name='resultscope'), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('bank_entry_id', sa.Uuid(), nullable=True),
    sa.Column('ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('MATCH', 'EXCEPTION', name='decision'), nullable=False),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('matcher_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bank_entry_id'], ['bank_entry.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entry.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('allocated_amount_paise', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('allocated_amount_paise > 0', name='ck_positive_allocation'),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'payment_id', name='uq_settlement_line_batch_payment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_line')
    op.drop_table('reconciliation_result')
    op.drop_index(op.f('ix_settlement_utr'), table_name='settlement')
    op.drop_table('settlement')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_ledger_entry_order_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('batch')
    op.drop_index(op.f('ix_bank_entry_utr'), table_name='bank_entry')
    op.drop_table('bank_entry')
    # ### end Alembic commands ###
