from __future__ import annotations
import enum

class BatchStatus(str, enum.Enum):
    CREATED = "CREATED"
    INGESTING = "INGESTING"
    INGESTED = "INGESTED"
    RECONCILING = "RECONCILING"
    COMPLETED = "COMPLETED"
    FAILED_INGESTION = "FAILED_INGESTION"
    FAILED_RECONCILIATION = "FAILED_RECONCILIATION"

class ResultScope(str, enum.Enum):
    PAYMENT = "PAYMENT"
    ORPHAN_BANK_ENTRY = "ORPHAN_BANK_ENTRY"

class Decision(str, enum.Enum):
    MATCH = "MATCH"
    EXCEPTION = "EXCEPTION"

class MatchMethod(str, enum.Enum):
    EXACT_UTR = "EXACT_UTR"
    ORDER_ID_EXACT = "ORDER_ID_EXACT"
    AMOUNT_WITH_FEE_EQUATION = "AMOUNT_WITH_FEE_EQUATION"
    LLM_ASSISTED_NARRATION = "LLM_ASSISTED_NARRATION"

class ReasonCode(str, enum.Enum):
    PARTIAL_SETTLEMENT = "PARTIAL_SETTLEMENT"
    DUPLICATE_UTR = "DUPLICATE_UTR"
    MISSING_BANK_ENTRY = "MISSING_BANK_ENTRY"
    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    UNRESOLVED_AMBIGUOUS = "UNRESOLVED_AMBIGUOUS"

class WebhookEventStatus(str, enum.Enum):
    PROCESSED = "PROCESSED"
    SKIPPED_DUPLICATE = "SKIPPED_DUPLICATE"
    SKIPPED_UNHANDLED = "SKIPPED_UNHANDLED"
    FAILED = "FAILED"
